// ---------------------------------------------------------------------------
// Agent Documentation Builder (YAML)
// ---------------------------------------------------------------------------
// Assembles a structured YAML reference from extracted tokens, utilities,
// components, and a static JavaScript API definition. Output is optimized
// for AI agent consumption — compact, hierarchical, and comprehensive.
// ---------------------------------------------------------------------------

import yaml from 'js-yaml';
import type {
  AgentDocsInput,
  FoundationTokens,
  ThemeTokens,
  UtilityGroup,
  ComponentData,
} from '../types.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function buildAgentDocs(input: AgentDocsInput): string {
  const doc = {
    _meta: buildMeta(),
    tier_system: buildTierSystem(),
    foundation: buildFoundation(input.foundation),
    themes: buildThemes(input.themes),
    utilities: buildUtilities(input.utilities),
    components: buildComponents(input.components),
    javascript_api: buildJavaScriptApi(),
    patterns: buildPatterns(),
    accessibility: buildAccessibility(),
  };

  const header = [
    '# Soltana UI — Agent Reference',
    '# Auto-generated by @soltana-ui/tokens. Do not edit.',
    '',
  ].join('\n');

  return (
    header +
    yaml.dump(doc, {
      lineWidth: 120,
      noRefs: true,
      sortKeys: false,
      quotingType: '"',
    })
  );
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function buildMeta(): Record<string, unknown> {
  return {
    generated: new Date().toISOString(),
    source: 'packages/soltana-ui/dist/soltana-ui.css',
    purpose: 'Structured reference for AI coding agents',
  };
}

function buildTierSystem(): Record<string, unknown> {
  return {
    themes: ['dark', 'light', 'sepia', 'auto'],
    reliefs: ['flat', 'glassmorphic', 'skeuomorphic', 'neumorphic'],
    finishes: ['matte', 'frosted', 'tinted', 'glossy'],
    attributes: {
      theme: 'data-theme',
      relief: 'data-relief',
      finish: 'data-finish',
    },
    per_element_classes: [
      'theme-dark',
      'theme-light',
      'theme-sepia',
      'relief-flat',
      'relief-glassmorphic',
      'relief-skeuomorphic',
      'relief-neumorphic',
      'finish-matte',
      'finish-frosted',
      'finish-tinted',
      'finish-glossy',
    ],
    bridge_tokens: [
      '--shadow-color',
      '--highlight-color',
      '--accent-glow',
      '--channel-sheen-color',
      '--channel-tint-color',
      '--glass-opacity',
      '--relief-opacity',
      '--finish-opacity',
    ],
    breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' },
  };
}

function buildFoundation(f: FoundationTokens): Record<string, unknown> {
  return {
    radius: f.radius,
    shadow: f.shadow,
    typography: {
      families: f.fontFamily,
      sizes: f.fontSize,
      weights: f.fontWeight,
      letter_spacing: f.letterSpacing,
    },
    transitions: f.transition,
    easing: f.easing,
    z_index: f.z,
  };
}

function buildThemes(themes: Record<string, ThemeTokens>): Record<string, Record<string, string>> {
  const result: Record<string, Record<string, string>> = {};
  for (const [name, tokens] of Object.entries(themes)) {
    result[name] = {
      colorScheme: tokens.colorScheme,
      surfaceBg: tokens.surfaceBg,
      surface1: tokens.surface1,
      textPrimary: tokens.textPrimary,
      textSecondary: tokens.textSecondary,
      accentPrimary: tokens.accentPrimary,
      accentSecondary: tokens.accentSecondary,
      colorSuccess: tokens.colorSuccess,
      colorWarning: tokens.colorWarning,
      colorError: tokens.colorError,
      colorInfo: tokens.colorInfo,
    };
  }
  return result;
}

function buildUtilities(groups: UtilityGroup[]): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const group of groups) {
    result[group.category] = {
      description: group.description,
      responsive: group.responsive,
      ...group.classes,
    };
  }

  // Add responsive documentation
  result.responsive = {
    note: 'Breakpoint prefix before class: md:flex-col',
    covered: ['display', 'flex', 'grid', 'gap', 'padding', 'margin', 'sizing', 'text-align'],
    not_covered: ['visual', 'transforms', 'animations'],
  };

  return result;
}

function buildComponents(components: ComponentData[]): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const comp of components) {
    const key = comp.name.toLowerCase().replace(/\s+/g, '_');
    const entry: Record<string, unknown> = {
      base: comp.baseClass.replace(/^\./, ''),
      description: comp.description,
      tier_aware: comp.tierAware,
    };
    if (comp.variants.length > 0) entry.variants = comp.variants.map((v) => v.replace(/^\./, ''));
    if (comp.sizes.length > 0) entry.sizes = comp.sizes.map((s) => s.replace(/^\./, ''));
    if (comp.children.length > 0) entry.children = comp.children.map((c) => c.replace(/^\./, ''));
    if (comp.example) entry.example = comp.example;
    result[key] = entry;
  }
  return result;
}

function buildJavaScriptApi(): Record<string, unknown> {
  return {
    init: {
      function: 'initSoltana(config?)',
      returns: 'SoltanaInstance',
      config_fields: ['theme', 'relief', 'finish', 'overrides', 'enhancers', 'strict'],
    },
    instance_methods: [
      { method: 'getState()', returns: 'SoltanaConfig' },
      { method: 'setTheme(name)', description: 'Switch active theme' },
      { method: 'setRelief(name)', description: 'Switch active relief' },
      { method: 'setFinish(name)', description: 'Switch active finish' },
      { method: 'setOverrides(record)', description: 'Inject CSS custom properties' },
      { method: 'removeOverrides(keys)', description: 'Remove CSS custom property overrides' },
      { method: 'registerTheme(name, options)', description: 'Runtime theme from seed colors' },
      { method: 'registerRelief(name, options)', description: 'Runtime relief from token map' },
      { method: 'registerFinish(name, options)', description: 'Runtime finish from token map' },
      { method: 'reinitEnhancers()', description: 'Destroy and re-create JS enhancers' },
      { method: 'reset()', description: 'Reset all tiers to defaults' },
      { method: 'destroy()', description: 'Tear down instance and remove all attributes' },
    ],
    registration: {
      theme_seed: {
        required: ['surfaceBg', 'textPrimary', 'accentPrimary'],
        optional: [
          'colorScheme',
          'accentDecorative',
          'colorSuccess',
          'colorWarning',
          'colorError',
          'colorInfo',
          'highlightColor',
        ],
      },
      relief_tokens: [
        '--relief-bg',
        '--relief-shadow-sm',
        '--relief-shadow',
        '--relief-shadow-lg',
        '--relief-shadow-inset-sm',
        '--relief-shadow-inset',
        '--relief-shadow-inset-lg',
        '--relief-border',
        '--relief-opacity',
      ],
      finish_tokens: [
        '--finish-blur',
        '--finish-saturation',
        '--finish-opacity',
        '--finish-overlay',
        '--finish-sheen',
      ],
    },
    enhancers: [
      { function: 'initModals', selector: '[data-sol-modal]' },
      { function: 'initTabs', selector: '[data-sol-tabs]' },
      { function: 'initTooltips', selector: '[data-sol-tooltip]' },
    ],
    events: {
      name: 'soltana:change',
      detail: {
        type: ['theme', 'relief', 'finish', 'overrides', 'reset', 'destroy'],
        value: 'unknown',
      },
    },
    postcss_plugin: {
      function: 'soltanaTreeshake',
      options: {
        themes: '{ include?: string[], exclude?: string[] }',
        reliefs: '{ include?: string[], exclude?: string[] }',
        finishes: '{ include?: string[], exclude?: string[] }',
      },
    },
    fonts: {
      function: 'loadSoltanaFonts(url?)',
      default_families: ['Cinzel', 'Cinzel Decorative', 'Raleway', 'JetBrains Mono'],
    },
  };
}

function buildPatterns(): Record<string, unknown> {
  return {
    tier_composition: [
      { theme: 'dark', relief: 'glassmorphic', finish: 'frosted', use: 'Modern overlay panels' },
      { theme: 'sepia', relief: 'skeuomorphic', finish: 'matte', use: 'Vintage document UIs' },
      { theme: 'light', relief: 'neumorphic', finish: 'matte', use: 'Soft minimal dashboards' },
      { theme: 'dark', relief: 'flat', finish: 'glossy', use: 'High-contrast data displays' },
    ],
    responsive_layout: [
      { pattern: 'Mobile-first stack', classes: 'flex flex-col md:flex-row gap-4' },
      {
        pattern: 'Responsive card grid',
        classes: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
      },
      { pattern: 'Centered content', classes: 'flex items-center justify-center min-h-screen' },
    ],
    common_compositions: {
      card_grid: {
        html: [
          '<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">',
          '  <div class="card card-hover"><div class="card-body">…</div></div>',
          '</div>',
        ].join('\n'),
      },
      form: {
        html: [
          '<form class="flex flex-col gap-4 max-w-md">',
          '  <input class="input" type="text" placeholder="Name" />',
          '  <button class="btn btn-primary">Submit</button>',
          '</form>',
        ].join('\n'),
      },
      nav_with_content: {
        html: [
          '<div class="app-layout">',
          '  <header class="app-header">…</header>',
          '  <aside class="sidebar">…</aside>',
          '  <main class="main"><div class="main__content">…</div></main>',
          '</div>',
        ].join('\n'),
      },
    },
  };
}

function buildAccessibility(): Record<string, unknown> {
  return {
    classes: ['sr-only', 'skip-link', 'focus-ring'],
    features: [
      'prefers-reduced-motion: disables animations',
      'prefers-contrast: increases border contrast',
      'All interactive components have visible focus states',
      'Enhancers add ARIA attributes and keyboard navigation',
    ],
  };
}
